version: 2
jobs:
  generate_jobs_yaml:
    docker:
      - image: circleci/python:3.6.8
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: Install boto3
          command: 'pip install --user boto3'
      - run:
          name: Generate yaml file with jobs
          command: 'python scripts/get-jobs.py'
      - persist_to_workspace:
          root: ~/workspace
          paths: .
  build_site:
    docker:
      - image: circleci/ruby:2.6.0
    working_directory: ~/workspace
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Install jekyll
          command: |
            sudo apt-get install ruby-full build-essential zlib1g-dev
            gem install jekyll bundler jekyll-timeago
      - run:
          name: Build site
          command: 'jekyll build'
      - persist_to_workspace:
          root: ~/workspace
          paths: .
  deploy_and_invalidate_cloudfront_cache:
    docker:
      - image: circleci/python:3.6.8
    working_directory: ~/workspace
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Install awscli
          command: 'sudo apt-get install awscli'
      - run:
          name: Deploy to S3
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync ./_site  s3://www.payrolled.fi --delete --acl public-read
            else
              echo "Not master branch, dry run only"
            fi
      - run: 
          name: Invalidate CloudFront cache
          command: |
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id $WWW_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
            aws cloudfront create-invalidation --distribution-id $NON_WWW_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

workflows:
  version: 2
  deploy_site:
    triggers:
      - schedule:
          cron: "45 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - generate_jobs_yaml
      - build_site:
          requires:
            - generate_jobs_yaml
      - deploy_and_invalidate_cloudfront_cache:
          requires:
            - build_site
